services:

  fraand_front:
    build:
      context: .
      args:
        - REACT_APP_API_BASE_URL = $REACT_APP_API_BASE_URL
      tags:
        - latest
    env_file:
      - .env
    labels:
      caddy: fraand.org
      caddy.reverse_proxy: "{{upstreams $REACT_DOCKER_PORT}}"
