name: Deploy to Nether Land

on:
  push:
    branches: [ docker-compose ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Code Checks
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH public key
        run: |
          mkdir .ssh/
          echo "${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}" > .ssh/id_ed25519 
          echo "${{ secrets.NL_FRONT_DEPLOYMENT_PUBLIC_KEY }}" > .ssh/id_ed25519.pub

      - name: Add DigitalOcean to known hosts
        run: ssh-keyscan ${{ secrets.DIGITALOCEAN_IP }} >> .ssh/known_hosts          

      - name: SSH into DigitalOcean droplet and deploy Docker Compose stack
        run: |
          ssh -v -i .ssh/id_ed25519 -o UserKnownHostsFile=.ssh/known_hosts ${{ secrets.SSH_USERNAME }}@${{ secrets.DIGITALOCEAN_IP }} 'ls -arl . && touch test'          

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}
#          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}/"
          