name: Code Quality

on:
  push:
    branches: [ docker-compose ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Code Checks
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH private key
        run: |
          mkdir .ssh/
          echo "${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}" > .ssh/id_rsa && chmod 600 .ssh/id_rsa
          echo ${{ secrets.NL_FRONT_DEPLOYMENT_PUBLIC_KEY }} > .ssh/id_rsa.pub

      - name: Add DigitalOcean to known hosts
        run: ssh-keyscan ${{ secrets.DIGITALOCEAN_IP }} >> .ssh/known_hosts

      - name: SSH into DigitalOcean droplet and deploy Docker Compose stack
        run: |
          scp -r docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.DIGITALOCEAN_IP }}:/home/${{ secrets.SSH_USERNAME }}/docker-compose.yml
          