name: Deploy to Nether Land

on:
  push:
    branches: [ docker-compose ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Code Checks
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH public key
        run: |
          mkdir ~/.ssh/ && chmod 700 ~/.ssh/
          echo "${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519

      - name: Add DigitalOcean to known hosts
        run: ssh-keyscan ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts          

      - name: SSH into DigitalOcean droplet and deploy Docker Compose stack
        run: |
          ssh -vvv -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.DIGITALOCEAN_IP }} 'ls -arl . && touch test'

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}/"
          
