name: Code Quality

on:
  push:
    branches: [ docker-compose ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Code Checks
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean droplet and deploy Docker Compose stack
        run: |
          echo ${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }} > id_rsa
          scp -i id_rsa -r docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.DIGITALOCEAN_IP }}:/home/${{ secrets.SSH_USERNAME }}/docker-compose.yml
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.DIGITALOCEAN_IP }} 'cd /path/to && docker-compose up -d'