name: Deploy to Nether Land

on:
  push:
    branches: [ docker-compose ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Code Checks
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH public key
        run: echo "${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}" > ~/.ssh/id_rsa.pub

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.NL_FRONT_DEPLOYMENT_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}/"
          